### ISSUE TITLE
在android stdio中解析并下载到设备上，运行时出现以下错误，请问怎么解决？

### ISSUE THREAD

**Issue by beckchen522** [luojinlongjjj/android-faiss#1]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.datamachines.faiss, PID: 9165
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libomp.so" not found
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at io.datamachines.faiss.MainActivity.<clinit>(MainActivity.java:15)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:742)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:632)

**Comment by luojinlongjjj** [comment]
估计是ndk版本问题   我用的是 android-ndk-r19c

**Comment by beckchen522** [comment]
确实是ndk版本的问题，我换了和你一样的ndk版本，可以运行了，非常感谢。
